const DB_KEY="student_attendance_v1";
let db=JSON.parse(localStorage.getItem(DB_KEY)||'{"students":[],"attendance":[]}');
let currentQR=null, scanner=null;

function save(){localStorage.setItem(DB_KEY,JSON.stringify(db));}
function id(){return "STU-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7).toUpperCase();}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");if(id==="scan"){renderToday()}if(id==="reports"){renderReport()}}
function addStudent(){
 const roll=document.getElementById("roll").value.trim(), name=document.getElementById("name").value.trim(), cls=document.getElementById("className").value.trim(), div=document.getElementById("division").value.trim(), email=document.getElementById("email").value.trim();
 if(!roll||!name){return msg("Roll No and Name are required","error")}
 if(db.students.some(s=>s.rollNo.toLowerCase()===roll.toLowerCase()))return msg("Roll No already exists","error");
 db.students.push({id:id(),rollNo:roll,name,className:cls,division:div,email,qrId:"STU-"+crypto.randomUUID()});save();
 ["roll","name","className","division","email"].forEach(x=>document.getElementById(x).value="");msg("Student added","ok");renderStudents();
}
function msg(t,c){let e=document.getElementById("msg");e.textContent=t;e.className=c||""}
function renderStudents(){
 const q=(document.getElementById("search").value||"").toLowerCase(), arr=db.students.filter(s=>[s.rollNo,s.name,s.className,s.division,s.email].join(" ").toLowerCase().includes(q));
 document.getElementById("count").textContent=`${db.students.length} students`;
 document.getElementById("studentList").innerHTML=arr.map(s=>`<div class="student"><div><b>${esc(s.rollNo)} - ${esc(s.name)}</b><small>Class ${esc(s.className)} ${esc(s.division)} • ${esc(s.email||"No email")}</small><small>QR: ${esc(s.qrId)}</small></div><div class="actions"><button onclick="showQR('${s.id}')">QR</button><button onclick="sendEmail('${s.id}')">Email QR</button><button class="danger" onclick="deleteStudent('${s.id}')">Delete</button></div></div>`).join("")||"<p>No students found.</p>";
}
function deleteStudent(sid){let s=db.students.find(x=>x.id===sid);if(!s)return;if(!confirm(`Delete ${s.name}? Attendance records will also be deleted.`))return;db.students=db.students.filter(x=>x.id!==sid);db.attendance=db.attendance.filter(x=>x.studentId!==sid);save();renderStudents()}
function showQR(sid){currentQR=db.students.find(s=>s.id===sid);if(!currentQR)return;document.getElementById("qrTitle").textContent=currentQR.name;document.getElementById("qrText").textContent=currentQR.qrId;document.getElementById("qr").innerHTML="";new QRCode(document.getElementById("qr"),{text:currentQR.qrId,width:240,height:240});document.getElementById("qrModal").classList.remove("hidden")}
function closeQR(){document.getElementById("qrModal").classList.add("hidden")}
function qrCanvas(){return document.querySelector("#qr canvas")||document.querySelector("#qr img")}
function downloadQR(){let el=qrCanvas();if(!el)return;let a=document.createElement("a");a.download=`${currentQR.rollNo}_${currentQR.name}_QR.png`;a.href=el.tagName==="CANVAS"?el.toDataURL():el.src;a.click()}
function emailQR(){if(!currentQR)return;sendEmail(currentQR.id)}
function sendEmail(sid){
 const s=db.students.find(x=>x.id===sid);if(!s)return;
 if(!s.email)return alert("No email saved for this student.");
 const subject=encodeURIComponent("Your Student Attendance QR Code");
 const body=encodeURIComponent(`Hello ${s.name},\n\nYour attendance QR ID is: ${s.qrId}\n\nPlease keep your QR code safe. This email was generated by the Student Attendance system.\n\nNote: This free browser version opens your email app; it does not silently send an attachment.`);
 window.location.href=`mailto:${encodeURIComponent(s.email)}?subject=${subject}&body=${body}`;
}
async function startScanner(){
 if(scanner)return;
 scanner=new Html5Qrcode("reader");
 try{await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:250}},text=>markAttendance(text),()=>{});}
 catch(e){document.getElementById("scanMsg").textContent="Camera could not start. Use HTTPS/localhost and allow camera permission."}
}
async function stopScanner(){if(scanner){try{await scanner.stop();}catch(e){}scanner=null}}
function markAttendance(qr){
 const s=db.students.find(x=>x.qrId===qr);
 if(!s){document.getElementById("scanMsg").textContent="Unknown QR";return}
 const now=new Date(), date=now.toISOString().slice(0,10), time=now.toLocaleTimeString();
 if(db.attendance.some(a=>a.studentId===s.id&&a.date===date)){document.getElementById("scanMsg").textContent=`Already marked today: ${s.name}`;return}
 db.attendance.push({id:id(),studentId:s.id,date,time,status:"Present"});save();document.getElementById("scanMsg").textContent=`Present: ${s.name} • ${time}`;renderToday();
}
function renderToday(){const d=new Date().toISOString().slice(0,10);const rows=db.attendance.filter(a=>a.date===d).sort((a,b)=>b.time.localeCompare(a.time));document.getElementById("todayList").innerHTML=rows.map(a=>{let s=db.students.find(x=>x.id===a.studentId);return `<p>✅ <b>${esc(s?.rollNo)} - ${esc(s?.name)}</b> — ${esc(a.time)}</p>`}).join("")||"<p>No attendance yet today.</p>"}
function importCSV(ev){
 const f=ev.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean), head=lines.shift().split(",").map(x=>x.trim().toLowerCase());let added=0;
 lines.forEach(line=>{const v=parseCSVLine(line), o={};head.forEach((h,i)=>o[h]=v[i]||"");if(o.rollno&&o.name&&!db.students.some(s=>s.rollNo===o.rollno)){db.students.push({id:id(),rollNo:o.rollno,name:o.name,className:o.class||"",division:o.division||"",email:o.email||"",qrId:"STU-"+crypto.randomUUID()});added++}});save();renderStudents();alert(`${added} students imported.`)};r.readAsText(f)}
function parseCSVLine(l){let out=[],cur="",q=false;for(let i=0;i<l.length;i++){let c=l[i];if(c==='"')q=!q;else if(c===","&&!q){out.push(cur.trim());cur=""}else cur+=c}out.push(cur.trim());return out}
function downloadCSVTemplate(){const a=document.createElement("a");a.href="data:text/csv;charset=utf-8,rollNo,name,class,division,email%0A1,Rahul Patil,10,A,rahul@example.com%0A2,Priya Shah,10,A,priya@example.com";a.download="students_template.csv";a.click()}
function filteredAttendance(){let from=document.getElementById("fromDate").value,to=document.getElementById("toDate").value;return db.attendance.filter(a=>(!from||a.date>=from)&&(!to||a.date<=to))}
function renderReport(){const rows=filteredAttendance();document.getElementById("reportTable").innerHTML=`<table><tr><th>Roll</th><th>Name</th><th>Class</th><th>Date</th><th>Time</th><th>Status</th></tr>${rows.map(a=>{let s=db.students.find(x=>x.id===a.studentId);return `<tr><td>${esc(s?.rollNo)}</td><td>${esc(s?.name)}</td><td>${esc(s?.className)} ${esc(s?.division)}</td><td>${a.date}</td><td>${a.time}</td><td>${a.status}</td></tr>`}).join("")}</table>`}
function exportExcel(){let rows=filteredAttendance().map(a=>{let s=db.students.find(x=>x.id===a.studentId)||{};return {RollNo:s.rollNo,Name:s.name,Class:s.className,Division:s.division,Email:s.email,Date:a.date,Time:a.time,Status:a.status}});let ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Attendance");XLSX.writeFile(wb,"attendance_report.xlsx")}
function exportPDF(){let rows=filteredAttendance(),{jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(16);doc.text("Student Attendance Report",14,18);let y=30;doc.setFontSize(9);rows.forEach(a=>{let s=db.students.find(x=>x.id===a.studentId)||{};let line=`${s.rollNo||""} | ${s.name||""} | ${s.className||""} ${s.division||""} | ${a.date} ${a.time} | ${a.status}`;if(y>280){doc.addPage();y=18}doc.text(line.slice(0,110),14,y);y+=7});doc.save("attendance_report.pdf")}
function downloadBackup(){let a=document.createElement("a");a.href="data:application/json;charset=utf-8,"+encodeURIComponent(JSON.stringify(db,null,2));a.download="attendance_database_backup.json";a.click()}
function restoreBackup(ev){let f=ev.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.students||!x.attendance)throw 0;db=x;save();renderStudents();alert("Backup restored")}catch(e){alert("Invalid backup")}};r.readAsText(f)}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("fromDate").value=new Date(Date.now()-30*86400000).toISOString().slice(0,10);document.getElementById("toDate").value=new Date().toISOString().slice(0,10);document.getElementById("fromDate").onchange=renderReport;document.getElementById("toDate").onchange=renderReport;renderStudents();renderReport()});
